spring.application.name=lets-play

# MongoDB Connection String
spring.data.mongodb.uri=mongodb://root:secretpassword@localhost:27017/letsplay_db?authSource=admin

# Show Mongo Queries in Console (Optional for Dev)
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG